>N1;gi|45384517|ref|NM_204995.1|:1-3550
Gallus gallus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), mRNA
GCACATCGGGTCAGAGCGGGGGGCTCGGCTGCTCCGTATCCCCCCCGAGACTATGACTTCCAGTAAAATTGA
GATGCCAGGGGAGGTGAAGGCAGATCCTGCCGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTCT
CAACCTTGAAATCAAACACACGAAGATTTTTATCAATAATGAGTGGCAAAATTCTGAAAGCGGGAGAGTATT
CCCAGTATACAATCCAGCAACAGGAGAGCAGATCTGTGAGATCCAGGAAGCAGACAAGGTTGACACGGACAA
GGCAGTGAGAGCAGCTCGCCTTGCTTTTTCTCTGGGTTCAGTTTGGAGGAGAATGGATGCATCGGAAAGAGG
CCAACTTTTGGATAAACTGGCAGACTTGGTTGAAAGAGACAGGGCAGTTCTTGCTACTATGGAATCACTGAA
CAGTGGCAAACCATTCCTGCAAGCCTTCTACGTAGATCTTCAAGGAGTCATAAAAACCCTGAGGTATTACGC
TGGTTGGGCAGACAAAATCCATGGAATGACCATACCTGTAGATGGAGATTATTTTACGTTTACAAGACATGA
ACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTCC
AGCTCTGTGCTGCGGCAATACAGTAGTTATTAAACCAGCAGAACAAACACCACTCAGCGCTCTCTATATGGG
AGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGTGAATATTTTGCCAGGATTTGGTCCAATTGTTGG
TGCAGCAATAGCATCTCATGTGGGCATTGATAAAATTGCGTTTACTGGATCCACTGAGGTTGGGAAGCTGAT
CCAAGAAGCAGCTGGAAGGAGTAACTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATCAT
TTTTGCAGATGCTGATTTGGATTATGCTGTGGAACAAGCTCACCAGGGGGTCTTCTTCAATCAAGGTCAATG
CTGCACTGCAGGCTCAAGGATTTACGTGGAAGAATCAATCTATGAAGAGTTTGTTAGAAGAAGTGTAGAACG
TGCAAAGAGGAGAGTAGTAGGGAGTCCTTTTGACCCAACTACAGAACAAGGGCCACAGATTGATAAAAAACA
ATACAACAAGATCTTGGAACTGATTCAGAGCGGCATTACTGAAGGAGCAAAACTTGAATGTGGGGGTAAAGG
GCTAGGAAGAAAGGGCTTCTTCATTGAACCTACAGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCAA
GGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCGTGGATGAAGTCATAGAGAGAGCCAA
CAATTCTGACTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAAACAAGGCCCTGACAGTCTCTTCAGC
AATGCAGGCTGGGACAGTCTGGATAAATTGCTACAACGCCTTAAATGCCCAGAGTCCTTTTGGAGGATTCAA
AATGTCTGGCAATGGTAGAGAGATGGGTGAAAGCGGATTGAGAGAATATTCTGAAGTTAAAACAGTGACAAT
AAAGATCCCTCAGAAGAATTCCTAAAATGATGAAAGACCACATAGTGCAGAAGAGCACATCGTGCCACCCTC
TCATTCTTTATGGAGACCAGCACTCAGGAATAAAAAGTGTTACACAATATGTATTTAAGAAAATAAGTTGCA
GCATATGTACTGGGCACATAATTGCGTAACTAATGCAAACCAACTCTGCATGTTTTCATAAAACTCTCTTGA
GAATCATTACATCTTTATAAAACAAATCTTAACAAGATGAAGTTGCTGTTGGGCATCAGTAACAGTTCTAGC
TATAAAACCGCTGAACGCAAATGCATGCACACACACATTTATCTCTTCTTCAAATAAAATAAGTCACTGCTT
TCAAGTTGCCTTCTCAAATAGACCTGCCTTCTTCTAACATTCTTATTTCACACAGGGCTTTACAAAGCAGAT
TTGCCCGAAATGCTAGGATTGAACGTTAATCAAGTATCATGGATGTTCTTAAGAAAGGAAAGACTGAATTGT
AACCAGACGAAAAATTCTAGATAGGCAACTTTCCAATGAGCACGTTCACGTAAAGAGGTTAAACGAGGGAAC
TACAGTGTTATATGGACAACAAAACACTCTTACCAGTGAGATTTAACCCGCAGTGTTTTGGTTTTCAAACCT
TATTTCAACAATTATTTTATGGCTTGCTACAAGCAGAAATCACGGAATCATAGAATCACAAGGTTGGAAAGG
ACCTACAAGAACATCCTGTCCAACCGTCCTCCCATTACCCTTGCTACCACAAATCCTCCCTCACCTACAGGG
ACTCAAAAGGTTTTACCTGCTTGATAAAAAAGATGGCCAGACAGGGTGAGAGGGTGCTGAGAACAGGAACAG
CTCCCAAGGCTGCACAGAGCATTTTTCAGCTTTCACTGCCTGCCTAGTTGTGTTGTTGTTGTTGTCACTGTT
TCAGCTTTTTTTTCCTTCTTTTCTAAACAAGTATTTGCACACGTCTCCATTTGTTTGTCTGCTAGTAAAGTG
CTTGTGATTACACTGGGAATCATTCAGTACTCATTGCCACAGGAAGAACCCAGCAAAGAAGTCAGTTTAATT
TTACTATCTTATGCAATCAGAGCTTGCCATCTGCACTCTACTTGTGAGCCTTAGGTAGCTTACTGGCTGCTA
TTGTACTTTTCAAAGACATCTGGCTTTTGTTCAGCCCAAGATAAAATTATGAACAAGTTCTCTTAAAAGTGA
GATGTTTAAGACCTGCCACGCTATTTTCTGCTGCCTATAGAATCTCTTCCAACTTGCAATTAATTAACAAAC
TGAATATTATCTCCTTCTTCCTTCCAGCTGAAGAACTCCCCAACTTTTTTTAATGGTTTTCTTTATGTTTTA
ACTTAGAATTAAGACAATGTATTTTAAAAGGGTGATAATCTGCAGATAAGTTCTTGTGGAATTTAAGGACAA
AATGATGGCTCAGGGTAGGAGTTTCCCTTAGCTGCAGTCTGTACTTCAGCCTGTTGAAAACTCCAGCCCTGA
ACTCAGCAAGTCATCACTTCTGCACATTGCTTTTCTTTGTTCTCTGAACAGTTCCTCTTAGATTTGAAGTTG
TGTGTGTCCTTAAATATACTGCTGGACCAGCAAGAGTATCCAGCACTTTGTAGTGTTGTAGCCTCGATATTT
TGTATTTCTAACTCATGTCAATCTGTGTATGTGTTTTTAAAGCAATATATATATACATGATATTATTCAGAA
ATGACAGTGCATCCACAGACATGATATTATTCAGAAATGACAGTGCATCCACAGACATGAAAATGAATAAAA
TATTCCTGAGTTGTTAAATGCAAATGTCATGTACTTGTACTGTAGCGTATGTCAGAGTTAAGAGTACAGCAA
GTAAGAAATTAGTTCTCTTTAAACTGCAATATAAAATGTGGCAAAGGAGATTTTATTTCCTTTTGCCTATCT
ACTTAAAAAAAAAAAAAAAAAA*
>N1;gi|45384517|ref|NM_204995.1|:3295-3336
Gallus gallus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), mRNA
ACATGATATTATTCAGAAATGACAGTGCATCCACAGACATGA------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|45384517|ref|NM_204995.1|:3331-3372
Gallus gallus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), mRNA
ACATGATATTATTCAGAAATGACAGTGCATCCACAGACATGA------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|324983852|gb|HQ260987.1|:1-2301
Anser anser aldehyde dehydrogenase 1 family member A2 (ALDH1A2) mRNA, complete cds
ACATCAGGTCAGAGCGGGGGGCTCGGCTGTACTATAACCCCCCCCCCCCAAGACTATGACTTCCAGTAAAAT
TGAGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCAC
TCTCAACCTTGAAATCAAATACACCAAGATTTTTATCAATAATGAATGGCAAAATTCTGAAAGTGGGAGAAT
ATTCCCAGTATATAATCCAGCAACAGGAGAGCAGATCTGTGAGATCCAGGAAGCTGACAAGGTTGATACGGA
CAAAGCAGTGAGAGCTGCTCGCCTTGCTTTTTCTCTAGGTTCAGTTTGGAGGAGAATGGATGCATCGGAAAG
AGGCCATCTTTTGGATAAGCTAGCAGACTTGGTCGAAAGAGACAGGGCAACTCTTGCTACTATGGAATCACT
CAACAGTGGCAAACCTTTCTTGCAAGCTTTCTATGTAGATCTTCAAGGAGTCATAAAAACCCTGAGGTATTA
TGCTGGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACA
TGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTCTGCATGGAAGATTGC
TCCAGCTCTGTGTTGTGGCAATACAGTAGTTATTAAACCCGCAGAACAAACACCACTCAGCGCTCTCTATAT
GGGAGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGTCAATATTTTGCCAGGATTTGGTCCAATTGT
TGGTGCAGCTATAGCATCTCATGTTGGCATTGATAAAATTGCATTTACTGGATCTACTGAGGTTGGGAAGCT
GATCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACAT
TATTTTTGCAGATGCGGATTTGGACTATGCTGTGGAACAAGCTCACCAAGGAGTCTTCTTCAATCAAGGTCA
ATGCTGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAATCTATGAAGAGTTTGTAAGAAGAAGTGTAGA
ACGTGCGAAGAGGAGAGTAGTGGGGAGTCCTTTTGACCCAACTACAGAACAAGGTCCACAGATTGATAAAAA
ACAATACAACAAGATCTTGGAACTGATTCAAAGTGGCATTACTGAAGGAGCAAAACTTGAATGTGGGGGTAA
AGGGCTAGGAAGAAAGGGCTTCTTCATTGAACCTACGGTGTTTTCCAATGTAACAGATGACATGCGGATTGC
CAAGGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCATGGATGAAGTTATAGAGAGAGC
CAACAATTCTGACTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAAACAAAGCCCTGACAGTCTCTTC
AGCAATGCAGGCTGGGACAGTCTGGATAAACTGCTACAATGCCTTAAATGCCCAAAGTCCTTTTGGAGGATT
CAAAATGTCTGGCAATGGGAGAGAGATGGGTGGAAGTGGATTGAGAGAATATTCTGAAGTTAAAACTGTGAC
AATAAAGATCCCTCAGAAGAATTCCTAAAATGATGGAAGACCATGTTGTGCAGAAGAGCACATGATGCCACC
CTCTCTATTCTTTATGGAGACCAGCACTCAGGAATAAAAAGCATTACACAAAATGTATTTAAGAAATTAAGT
TGCAGCATATATACTGGGCACATAATTGCATAAGGAATGCAAACCAACTCTGCATGCTTTCATGAAACTCTC
TTGAGAGTTACATCTTTATAAAACTTACCATAACAAGATAAAGTTGCTATTGGACATCATTTAATAACAGTT
CTAGCTATAAAACTGGTAAATACAAATGCATGCATACACACATTTATCTCTTCTTTAAATAAACAAAATAAG
TCTTACTGCTTTCAAGTTGCCTTCTCAAACAGACCTGCCTTCTTCTGACATTCTTGTTTCATACAGGGCTTT
ACAAGCCAGATTTACCCAAAATGCTAGGAGCAAACAACATAATCAAGTACCATTCATGTTTTGAAAAAAATG
TAAGACTGTGAACAGTAACCAGCCCAAAATTGGTATACTGGCAACTTTCCAATTAGCATGCTCACATAAAGA
GGTTAAACTGGGGAAGGTACTAAATCATTATATGGACAATGAAATCCAAATACCATGAGATTTGGCTTTCAT
GACCCAGAGTGTTTTGGTTTTCAAAGCTTATTTTAATAATTATTTTATGGCTTGTTACAAGCAGAAATC---
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|324983852|gb|HQ260987.1|:2297-3290
Anser anser aldehyde dehydrogenase 1 family member A2 (ALDH1A2) mRNA, complete cds
AAATCCTCCCTCACTTACAGGGACTTAAAAGGCTTTACCTGCCTGCCAAAAGAGCATGGCCAGACAGGGTGG
AAGAGTGCTAAGAACAGGAACAGATCCCAAGGCTTCACAGAATATTTCAACTTTCATTGCCTGCTTAGCTTT
GTTGTTGTTGTTGCTGTCACTGTTGTTGTTTTCACTTTTTTTAAACAAGTATATGCACACACAGACTCCATT
TATTTGTCTGCTAGTAAACTGCTTGTGATTACACTGAGAATCATTAAGTATTCATTACCACAGGAAGAACCT
AGTGAAAGCCCACCTGTCAGGAAGTTAGCTTGATTTTATTTTCTTATTAAATTATGCTTTGCCATCCTTGCC
ATGCTTGTGTGCCTTAGGTGTACTTCCTGGCTAGTACTGTATTTTCATTGTTGTCTCTTTTTTGTTGAGCCC
AGGACAAAAATATGAACATGATCTTTTAGAAGTAAGATGTTTAAAACCTGACACACTATTTCCTGCTGCCTA
CAGAATCTCTTCCAACTTGCAATTAACGAACTAAACATTATCCCCTTCTTCTTTCTAGATGTAGAGCTCCCC
AGACTTTTTTTAAGGTTTCACTTTACGTTTTAACTTAGAATTAAGACAATGTATTTTAGAAGTACAGTAAAT
CATCTACTGTAGCTACATTCTGTGGGGTGTAAGGACAGAGTTATGGCCTCAGGTGTAGCAGTTCTCCTGGCT
GCAGAGTGTATACTACGAACTGTTGAAAACTCCAGACCTGATTTAGCAAATAGTTTCTGTACGTACTTAACT
TTCTTACTCTCTGAGCAATTCCTTGTAGATTTGAACTTGTGTGTGCCCTTAAATACACTGCAGGATCAGGAC
AACGGTATACAGCACTTTGTAGTGTTGTAGCCCTCAATATTTTCTAACTCGTGTCAATCTGTGTATCGTGTT
TTCAAAGCAATATGTATACACGATGTTATTCAGAAATGACAGTACATTCACAGACATG--------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|326926566|ref|XM_003209422.1|:217-2035
PREDICTED: Meleagris gallopavo retinal dehydrogenase 2-like (LOC100545801), mRNA
CTGCATCTGCTGCCTTCTCCCACTCTCAACCTTGAAATCAAACACACGAAGATTTTTATCAATAATGAGTGG
CAAAATTCTGAAAGTGGGAGAGTATTCCCAGTATACAATCCAGCAACAGGGGAGCAGATCTGTGAGATCCAG
GAAGCAGACAAGGCTGATACGGACAAAGCAGTGAGAGCAGCTCGCCTTGCTTTTTCTCTAGGTTCAGTTTGG
AGGAGAATGGACGCATCGGAAAGAGGCCAACTTTTGGATAAACTAGCAGACTTGGTCGAAAGAGACAGGGCA
GTTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCATTCCTGCAAGCCTTCTACGTAGATCTTCAAGGA
GTCATAAAAACCCTGAGGTATTATGCTGGTTGGGCAGACAAAATCCATGGAATGACCATACCTGTAGATGGA
GATTATTTTACGTTTACAAGACATGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTG
CTGATGTTTGCATGGAAGATTGCTCCAGCTCTGTGCTGTGGCAATACAGTGGTTATTAAACCAGCAGAACAA
ACACCACTCAGCGCTCTCTATATGGGAGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGTCAATATT
TTGCCAGGATTTGGTCCAGTTGTCGGTGCAGCAATAGCATCTCATGTGGGCATTGATAAAATTGCATTTACT
GGATCCACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGTAACTTGAAGAGAGTTACACTGGAG
CTGGGTGGGAAAAGCCCAAACATCATTTTTGCAGATGCTGATTTGGACTATGCTGTGGAACAAGCTCACCAG
GGGGTCTTCTTCAATCAAGGTCAATGCTGCACTGCAGGCTCAAGGATTTACGTGGAAGAATCAATCTATGAA
GAGTTTGTTAGAAGAAGTGTAGAACGTGCAAAGAGGAGAGTAGTAGGGAGTCCTTTTGACCCAACTACAGAA
CAAGGGCCACAGATTGATAAAAAACAATACAACAAGATCTTGGAACTGATTCAAAGCGGCATTACTGAAGGA
GCAAAACTTGAATGTGGGGGTAAAGGGCTAGGAAGAAAGGGCTTCTTCATTGAACCTACAGTGTTTTCCAAT
GTAACAGATGACATGCGGATTGCCAAAGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACC
CTGGATGAAGTTATCGAGAGAGCCAACAATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGATATA
AACAAGGCCCTGACAGTCTCTTCAGCAATGCAGGCTGGGACAGTCTGGATAAATTGCTACAACGCCTTAAAT
GCCCAAAGTCCTTTTGGAGGTTTCAAAATGTCTGGCAATGGTAGAGAGATGGGTGAAAGCGGATTGAGAGAA
TATTCTGAAGTTAAAACAGTGACAATAAAGATCCCTCAGAAGAATTCCTAAAATGATGCAAGACCGCAGAAG
AGCACATGATGCCACCCTCTCTGTTCTTTATGGAGACCAGCACTCAGGAATAAAAAGTGTTACACAATATGT
ATTTAAGAAAATAAGTTGCAGCATATGTACTGGGCACATAATTGCGTAACTAATGCAAACCAACTCTGCATG
TTTTCATAAAACTCTCTTGAGAATCATTACATCTTTATAAAACAAATCTTAACAAGATGAAGTTGCTGTTGG
GCATCAGTAACAGTTTTAGCTATAAAACCGTTGAACGCAAATGCATGCACACACACATTTATCTCTTCTTCA
AATAAAATAAGTCACTGCT-----------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|514713115|ref|XM_005011936.1|:1-2205
PREDICTED: Anas platyrhynchos aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
GATCCTGCAGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTCTCAACCTTGAAATCAAATACACC
AAGATTTTTATCAATAATGAGTGGCAAAATTCTGAAAGTGGGAGAATATTCCCAGTATATAATCCAGCAACA
GGAGAGCAGATCTGCGAGATCCAGGAAGCTGACAAGGTTGATACGGACAAAGCAGTGAGAGCTGCTCGCCTC
GCTTTTTCTCTAGGCTCAGTTTGGAGGAGAATGGATGCATCGGAAAGAGGCCATCTTTTGGATAAACTAGCA
GACTTGGTCGAAAGAGACAGGGCAACTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCTTTCTTGCAA
GCTTTCTATGTAGACCTTCAAGGAGTCATAAAAACCCTGAGGTATTATGCTGGTTGGGCAGACAAAATCCAT
GGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACATGAACCCATCGGAGTGTGTGGACAG
ATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTCCAGCTCTGTGCTGTGGCAATACA
GTAGTTATTAAACCTGCGGAACAAACACCACTCAGCGCTCTCTATATGGGAGCCCTCATCAAGGAGGCTGGC
TTTCCACCAGGAGTTGTCAATATTTTGCCAGGATTTGGTCCAATTGTTGGTGCAGCTATAGCATCTCATGTT
GGCATTGATAAAATTGCATTTACTGGATCTACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGC
AATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATTATTTTTGCAGATGCAGATTTGGAC
TATGCTGTGGAACAAGCTCACCAAGGAGTCTTCTTCAATCAAGGTCAATGCTGCACTGCAGGCTCACGGATT
TATGTGGAAGAATCAATCTATGAAGAGTTTGTAAGAAGAAGTGTAGAACGTGCAAAGAGGAGAGTAGTGGGG
AGTCCTTTTGACCCAACTACAGAACAAGGTCCACAGATTGATAAAAAACAATACAACAAGATCTTGGAACTG
ATTCAAAGTGGCATTACCGAAGGAGCAAAACTTGAATGTGGGGGTAAAGGGCTAGGAAGAAAGGGCTTCTTC
ATTGAACCTACGGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCAAGGAGGAGATTTTTGGGCCTGTT
CAAGAAATACTGAGGTTTAAAACCATGGATGAAGTTATAGAGAGAGCCAACAATTCTGACTTTGGGCTGGTA
GCTGCTGTCTTTACAAATGACATAAACAAAGCCCTGACGGTCTCTTCAGCAATGCAGGCTGGGACAGTCTGG
ATAAACTGCTACAATGCCTTAAATGCCCAAAGTCCTTTTGGAGGATTCAAAATGTCTGGCAATGGGAGAGAG
ATGGGTGAAAGTGGATTGAGAGAATATTCTGAAGTTAAAACTGTGACAATAAAGATCCCTCAGAAGAATTCC
TAAAATGATGGAAGACCATGTTGTGCAGAAGAGCACATGATGCCACCCTCTGTATTCTTTATGGAGACCAGC
ACTCAGGAATAAAAAGTGTTACACAAAATGTATTTAAGAAATTAAGTTGCAGCATATATACTGGGCACATAA
TTGCATAAGGAATGCAAACCAACTCTGCATGCTTTCATTAAACTCTCTTGAGAGTTACATCTTTATAAAACT
TACCATAACAAGATAAAGTTGCTATTGAACATCATTTAATAACAGTTCTAGTTATAAAACTGTTAAATTCAA
ATGCATGCATACACACATTTATCTCTTCTTTAAATAAACAAAGTAAGTCTTACTGCTTTCAAGTTGCCTTCT
CAAGCAGACCTGCCTTCTTCTGACATTCTTGTTTCATACAGGGCTTTACAAGCCAAATTTACCCAAAATACT
AGGATCAAACAACATAATCAAGTACCATTCGTGTTTTGAAAAAAAATGTAAGGCTGTGAACTGTAACCAGCC
CAAAACTGGTATATTGGCAACTTTCCAATTAGCATGCTCACATAAAGAGGTTAAACTGGGGAAGGTACTAAA
TCATTATATGGACAATGAAATCCAAATACCATGAGATTTGGCTTTCATGACCCAGAGTGTTTTGGTTTTCAA
AGCTTATTTTAATAATTATTTTATGGCTTGTTACAAGCAGAAATC---------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|527255368|ref|XM_005145910.1|:14-2274
PREDICTED: Melopsittacus undulatus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CCCCCCCGAGACTATGACTTCCAGTAAAATTGAGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGAT
GGCATCTCTGCATCTGCTGCCTTCTCCCACTCTCAACCTTGAAATCAAATACACCAAGATTTTCATCAATAA
TGAGTGGCAAAATTCTGAGAGTGGGAGAATATTCCCAGTATATAATCCAGCCACAGGAGAGCAGATCTGTGA
GATCCAGGAAGCTGACAAGGTTGATACAGACAAAGCAGTGAGGGCAGCTCGCCTCGCTTTTTCTCTCGGTTC
AGTCTGGAGGAGAATGGATGCATCAGAAAGAGGCCATCTTTTGGATAAGCTAGCAGACTTGGTTGAAAGAGA
CAGGGCAGTTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCTTTCTTGCAAGCTTTCTATGTAGATCT
TCAGGGAGTCATAAAAACCCTGAGGTATTATGCTGGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGT
AGATGGAGATTATTTTACGTTTACAAGACATGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTT
CCCCCTGCTGATGTTTGCATGGAAGATTGCTCCAGCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGC
AGAACAAACACCACTCAGTGCTCTCTATATGGGAGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGT
CAATATTTTGCCAGGATTTGGTCCAATTGCTGGTGCAGCCATAGCATCTCATGTTGGCATTGACAAAATTGC
TTTTACTGGATCCACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTAC
ACTGGAGCTGGGTGGGAAAAGCCCAAACATTATTTTTGCAGATGCTGATTTGGACTATGCTGTGGAACAAGC
TCACCAAGGGGTCTTCTTCAATCAAGGCCAATGCTGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAAT
CTACGAAGAGTTTGTTAAAAGAAGCGTAGAACGTGCAAAGAGAAGAGTTGTGGGGAGTCCTTTTGATCCAAC
CACAGAACAAGGTCCTCAGATTGATAAAAAACAATACAACAAGATCTTGGAACTGATTCAGAGTGGCATTAC
TGAAGGAGCAAAACTTGAATGTGGGGGCAAAGGGCTAGGAAGAAAGGGCTTCTTCATTGAACCAACGGTGTT
TTCCAATGTAACAGATGACATGCGGATTGCTAAGGAGGAGATTTTTGGGCCTGTTCAAGAAATATTGAGATT
TAAAACCATGGATGAAGTTATAGAGAGAGCCAACAATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAA
TGACATAAACAAGGCCCTGACAGTCTCTTCAGCAATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGC
CTTAAATGCCCAAAGTCCTTTTGGAGGATTCAAAATGTCTGGCAATGGGAGAGAGATGGGTGAATGCGGATT
GAGAGAATATTCTGAAATTAAAACTGTGACAATAAAGATCCCTCAGAAGAACTCCTAAAATGATGAAGGACC
ACCCTGTGCAGAAGAGCACATGATGCCACCCTCTCTATTGCTTATGGAGACCAGCACTCAGGAATAAAAAGC
GTTACACAATATATATTTAAAAAATTAAGTTGCAACTTATATTCTGGGCACATAACTGCGTCCCTAAAGCAA
ACCAGCTCTGCATGTTTTCACAAAACTCTCCTGAGAACCATAACATCTTTATAAAACAAATCATAACAAAAG
ATGAAATTGCTATTGGGCATCATTTAATAACAATTCTAGCTAGAAAACTGTTAAATGCAAATGCATGCACAC
ACACATTTATCTCTTCCTTAAATAAAGAAGTTTCAGTGCTTTCAGGTTGTCTTCTCAAACAGACCTGCCTGG
TACTGACATTCTAGATTCAATCATGGCTTTACAAGCCAGATTCTACCCAAAACACTAGCAATGAACAACATA
AGTAACATTGATGTTCTTAAAAAAATCAAAAACTCTGAGCAGTAATGAGCCAACAGCTAATATATTGGCAAC
ATTCCAATTAGCATGCTCACATAAAGAGATCAAACTAGGGAGGGAATCAAACCATTATATGGACAACAAAAT
CCAAATACTTATCAGTGAGATTTGAATTTCACAACCCAAAGTGATTTCATTTTCAAAGCTTATTTTCATAAT
TAGTTTTTGTCTTGCATTAAGCAAAAATC-------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|527255368|ref|XM_005145910.1|:3213-3431
PREDICTED: Melopsittacus undulatus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
ACATAATGTTATTCAGAAATGACAGTACATTTGCAGACATGGAGATGAATCAAAATATTCCTGAGTTGTTAA
ATGCAAATGCCATATAGTTTGAAATGTAGTGTACGTCAGAGTGAAGAAAACCAAAATACAGCAAGTAAGAGA
TTAGTTATCTTTTAAACTGCAATACAAAATCTGAAAAAGGAGATTTTAATTCTTTTCTCCTATTTACTTAAA
AAA---------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|529421624|ref|XM_005230611.1|:3-2123
PREDICTED: Falco peregrinus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
AGACTATGACTTCCAGTAAAATTGAGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGATGGCATCTC
TGCATCTGCTGCCTTCTCCCACTCTCAACCTTGAAATCAAATACACCAAGATTTTCATCAATAATGAGTGGC
AAAATTCTGAAAGTGGGAGAACATTCCCAGTATATAATCCAGCAACAGGAGAGCAGATCTGTGAGATCCAGG
AAGCTGACAAGGTTGATACGGACAAAGCAGTGAGGGCAGCTCGCCTGGCTTTTTCTCTAGGTTCGGTCTGGA
GAAGAATGGATGCATCGGAAAGAGGCCATCTTTTGGATAAGCTAGCAGATTTGGTCGAAAGAGACAGGGCAA
TTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCTTTCTTGCAAGCTTTCTATGTTGATCTTCAGGGAG
TCATAAAAACCCTGAGGTATTATGCCGGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAG
ATTATTTTACGTTTACAAGACACGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGC
TGATGTTTGCATGGAAGATTGCTCCAGCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGCAGAACAAA
CACCACTCAGCGCTCTCTATATGGGAGCCCTCATCAAGGAGGCTGGGTTTCCACCAGGAGTTGTCAATATTT
TGCCAGGATTTGGTCCAATTGTTGGTGCGGCCATAGCATCTCATGTTGGCATCGATAAAATTGCTTTTACTG
GATCCACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGC
TGGGTGGGAAAAGCCCAAACATTATTTTTGCAGATGCTGATTTGGACTATGCTGTGGAACAAGCTCACCAAG
GGGTCTTCTTCAATCAAGGTCAATGCTGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAATCTATGAAG
AGTTTGTTAGACGAAGCGTAGAACGTGCAAAGAGGAGAGTTGTGGGGAGCCCTTTTGACCCAACTACAGAAC
AAGGTCCACAGATTGATAAGAAACAGTACAACAAGATCTTGGAACTGATTCAAAGTGGCATTACTGAAGGAG
CAAAACTTGAATGTGGGGGCAAAGGGCTAGGAAGAAAGGGCTTCTTCATTGAACCTACAGTGTTTTCCAATG
TAACAGATGACATGCGGATTGCCAAGGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCA
TGGATGAAGTTATAGAGAGAGCCAACAATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAA
ACAAGGCCCTGACAGTCTCTTCAGCAATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGCCTTAAATG
CCCAAAGTCCTTTTGGAGGATTCAAAATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGACTGAGAGAAT
ATTCTGAAGTTAAAACTGTGACAATAAAGATCCCTCAGAAGAACTCCTAAAATGACAAAGGACCACATTGTG
CAGAAGAGCACATGATGCCACCCTCTCTATTCCTTATGGAGACCAGCACTCAGGAACAAAAAGTGTTACACA
ATATATATATAAGAAATTAAGTTGCAACATATATACCGGGCACATAACTACGTACATAATGCAAACCAGCTC
TGCATGTTTTCATAACACTCGCCTGAGAATCATTACATCTTTAAAAAACAAATTATAACAAGAGATAAAATT
GTTATCGGACATGATTTAATAACGGTTCTAGTATAAAACTGTTAAATGCAAATGCATGCACACACACATTTA
TCTCTTCTTTAAATAAACAAAGTAAGTCTTACTGCTTTCAGGTTGCCTTCTCAAACAGACCTGCCTTGTACT
GATACTCTAGTTTCAATCAGGGCTTTACAAGACAGATTTAATCCATAATGCTAGCAATGAACAACATAAACA
AGTACCATTGATGTTCTTAAAAAGTAAACAGACTGAACAGTAACGAGTCAAAAGCTGGTATACTGGCAACTT
TCCAATTAGCATGCTCCCATAAAGAGGTCAAAC---------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|529421624|ref|XM_005230611.1|:2241-3254
PREDICTED: Falco peregrinus aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CCTTGCTAAAGCAAAAATCCTCCCTCACTTACAGGAACTTGAAAGGTTTTACCTGCCTGCCAAAAAGCATGG
CCAGACAGGGTGCGAGGGTGTTAAGGAGAACAGGAACAGATCCCAAGGCTTCACAGAGTATCTCAGCTTTCA
CTGCTTGTCTAGTTCTGTTGTTGTTGTTGTTACTGTTGTTGTTTTCACCTTTCAAGTATATGCACACAGACT
CCCATTTATTTTTCTGCTATTAAACTGCCTGTGATTACACTGGGAATTATTTAAGTACTTGTTACAGCAGGA
GGAACCCAGCAAAAGCCCACCTGACAAGAAGTAAGCTTGACTTTCTTTTCTTGCTAAACGATGGCTTGCCAT
CCTCAGCACGCTTGTAAGCCTCAGGTGACCTTACTGGCTGGTACTGGCTTTTCAATTATGTCTGTTCTTTGT
TTTTGACCCAGGACAAAAATATGAGCAAGTTCTTTTAGAGTGAGGTGTTTAAAACCTGTCACATTATTACCT
GCTGCCTACAGAATCTCTTCCAACTTGTAACTAACAAACTAAACACCATCTCTTTCTTCTTTCCAGCTGCAG
AGCTCATCGATTCCCCAGACTTCTTTTAAAGAGGTTTCATTTTATGTTTTAACTTAGAATTAAGAAAATTTA
TTTTAAAAGTACAGTAAATCATCTATGCTGCGTAGCTACATTATCTGGGGTATAAGGACAGAATTACGGCCT
CAGGTGTAAGTTTTCCTAGCTGCAGAGTCTATACTATGAACTGTTGAAAACTCCAGACCTGATCAGCAAATC
ATTTCTGCATGTTCTTAACTTCCTTTACTCTCTGAGGAATTCCTCTTAGATTTGAAGTTGTGTGTGTCCTTA
AACATACTGCTGGATCAGGACAAGAGTATCCAGCACTTTGTGGTGTGGTGGCCCTCAATATTTTGTATTTCT
AACTCATGTCAAACGTGTGTTTTTAAAGCAATATGTATACATGATGTTATTCAGAAATGACGTACATTCACA
AACATG------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|541959605|ref|XM_005435487.1|:2-2122
PREDICTED: Falco cherrug aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
AGACTATGACTTCCAGTAAAATTGAGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGATGGCATCTC
TGCATCTGCTGCCTTCTCCCACTCTCAACCTTGAAATCAAATACACCAAGATTTTCATCAATAATGAGTGGC
AAAATTCTGAAAGTGGGAGAACATTCCCAGTATATAATCCAGCAACAGGAGAGCAGATCTGTGAGATCCAGG
AAGCTGACAAGGTTGATACGGACAAAGCAGTGAGGGCAGCTCGCCTGGCTTTTTCTCTAGGTTCGGTCTGGA
GAAGAATGGATGCATCGGAAAGAGGCCATCTTTTGGATAAGCTAGCAGATTTGGTCGAAAGAGACAGGGCAA
TTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCTTTCTTGCAAGCTTTCTATGTTGATCTTCAGGGAG
TCATAAAAACCCTGAGGTATTATGCCGGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAG
ATTATTTTACGTTTACAAGACACGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGC
TGATGTTTGCATGGAAGATTGCTCCAGCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGCAGAACAAA
CACCACTCAGCGCTCTCTATATGGGAGCCCTCATCAAGGAGGCTGGGTTTCCACCAGGAGTTGTCAATATTT
TGCCAGGATTTGGTCCAATTGTTGGTGCGGCCATAGCATCTCATGTTGGCATCGATAAAATTGCTTTTACTG
GATCCACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGC
TGGGTGGGAAAAGCCCAAACATTATTTTTGCAGATGCTGATTTGGACTATGCTGTGGAACAAGCTCACCAAG
GGGTCTTCTTCAATCAAGGTCAATGCTGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAATCTATGAAG
AGTTTGTTAGACGAAGCGTAGAACGTGCAAAGAGGAGAGTTGTGGGGAGCCCTTTTGACCCAACTACAGAAC
AAGGTCCACAGATTGATAAGAAACAGTACAACAAGATCTTGGAACTGATTCAAAGTGGCATTACTGAAGGAG
CAAAACTTGAATGTGGGGGCAAAGGGCTAGGAAGAAAGGGCTTCTTCATTGAACCTACAGTGTTTTCCAATG
TAACAGATGACATGCGGATTGCCAAGGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCA
TGGATGAAGTTATAGAGAGAGCCAACAATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAA
ACAAGGCCCTGACAGTCTCTTCAGCAATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGCCTTAAATG
CCCAAAGTCCTTTTGGAGGATTCAAAATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGACTGAGAGAAT
ATTCTGAAGTTAAAACTGTGACAATAAAGATCCCTCAGAAGAACTCCTAAAATGACAAAGGACCACATTGTG
CAGAAGAGCACATGATGCCACCCTCTCTATTCCTTATGGAGACCAGCACTCAGGAACAAAAAGTGTTACACA
ATATATATATAAGAAATTAAGTTGCAACATATATACCGGGCACATAACTACGTACATAATGCAAACCAGCTC
TGCATGTTTTCATAACACTCGCCTGAGAATCATTACATCTTTAAAAAACAAATTATAACAAGAGATAAAATT
GTTATCGGACATGATTTAATAACGGTTCTAGTATAAAACTGTTAAATGCAAATGCATGCACACACACATTTA
TCTCTTCTTTAAATAAACAAAGTAAGTCTTACTGCTTTCAGGTTGCCTTCTCAAACAGACCTGCCTTGTACT
GATACTCTAGTTTCAATCAGGGCTTTGCAAGACAGATTTAATCCATAATGCTAGCAATGAACAACATAAACA
AGTACCATTGATGTTCTTAAAAAGTAAACAGACTGAACAGTAACGAGTCAAAAGCTGGTATACTGGCAACTT
TCCAATTAGCATGCTCCCATAAAGAGGTCAAAC---------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|541959605|ref|XM_005435487.1|:2240-3255
PREDICTED: Falco cherrug aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CCTTGCTAAAGCAAAAATCCTCCCTCACTTACAGGAACTTGAAAGGTTTTACCTGCCTGCCAAAAAGCATGG
CCAGACAGGGTGCGAGGGTGTTAAGGAGAACAGGAACAGATCCCAAGGCTTCACAGAGTATCTCAGCTTTCA
CTGCTTGTCTAGTTCTGTTGTTGTTGTTGTTACTGTTGTTGTTTTCACCTTTCAAGTATATGCACACAGACT
CCCATTTATTTTTCTGCTATTAAACTGCCTGTGATTACACTGGGAATTATTTAAGTACTTGTTACAGCAGGA
GGAACCCAGCAAAAGCCCACCTGACAAGAAGTAAGCTTGACTTTCTTTTCTTGCTAAACGATGGCTTGCCAT
CCTCAGCACGCTTGTAAGCCTCAGGTGACCTTACTGGCTGGTACTGGCTTTTCAATTATGTCTGTTCTTTGT
TTTTGACCCAGGACAAAAATATGAGCAAGTTCTTTTAGAGTGAGGTGTTTAAAACCTGTCACATTATTACCT
GCTGCCTACAGAATCTCTTCCAACTTGTAACTAACAAACTAAACACCATCTCTTTCTTCTTTCCAGCTGCAG
AGCTCATCGATTCCCCAGACTTCTTTTAAAGAGGTTTCATTTTATGTTTTAACTTAGAATTAAGAAAATTTA
TTTTAAAAGTACAGTAAATCATCTATGCTGCGTAGCTACATTATCTGGGGTATAAGGACAGAATTACGGCCT
CAGGTGTAACAGTTTTCCTAGCTGCAGAGTCTATACTATGAACTGTTGAAAACTCCAGACCTGATCAGCAAA
TCATTTCTGCATGTTCTTAACTTCCTTTACTCTCTGAGGAATTCCTCTTAGATTTGAAGTTGTGTGTGTCCT
TAAACATACTGCTGGATCAGGACAAGAGTATCCAGCACTTTGTGGTGTGGTGGCCCTCAATATTTTGTATTT
CTAACTCATGTCAAACGTGTGTTTTTAAAGCAATATGTATACATGATGTTATTCAGAAATGACGTACATTCA
CAAACATG----------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|543740632|ref|XM_005511143.1|:42-2341
PREDICTED: Columba livia aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
ACATCAGGTCAGAGCGGGGGACTCGGTGCTGCTATAAAACCCCCCCCAAGAGTATGACTTCAAGTAAAATTG
AGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTC
TCAACCTTGAAATCAAATACACCAAGATTTTTATCAACAATGAGTGGCAAAATTCTGAAAGTGGGAGAATAT
TCCCAGTATATAATCCAGCAACAGGAGAGCAGATCTGTGAGATCCAGGAAGCTGACAAGGCTGATACAGACA
AAGCCGTGAGGGCAGCTCGCCTTGCCTTCTCTCTGGGTTCAGTCTGGAGGAGGATGGATGCATCGGAGAGAG
GCCATCTTTTGGACAAGCTAGCGGACCTGGTCGAAAGAGACAGAGCGATTCTTGCTACTATGGAATCACTGA
ACAGCGGCAAACCTTTCTTGCAAGCTTTCTATGTAGATCTCCAGGGGGTCATAAAAACCCTGAGGTATTATG
CTGGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACACG
AACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTC
CGGCTTTGTGCTGCGGCAATACAGTAGTTATTAAACCAGCAGAACAAACACCACTCAGTGCTCTCTATATGG
GAGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGCGTTGTCAATATTTTGCCAGGATTTGGTCCAATTGTTG
GTGCAGCCATAGCATCTCATGTTGGCATTGATAAAATTGCTTTTACTGGATCCACTGAGGTTGGGAAGCTGA
TCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATTA
TTTTCGCAGATGCTGATTTGGACTACGCTGTGGAACAAGCTCACCAAGGGGTCTTCTTCAATCAAGGTCAAT
GCTGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAATCTATGAAGAGTTTGTTAGAAGAAGTGTAGAAC
GTGCAAAGAGGAGAGTAGTGGGGAGTCCTTTTGACCCAACTACGGAACAAGGTCCACAGATTGATAAAAAAC
AATACAACAAGATCTTGGAACTGATTCAAAGCGGCATTACTGAAGGAGCAAAACTTGAATGTGGGGGTAAAG
GGCTAGGAAGAAAGGGCTTCTTCATTGAACCCACCGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCA
AGGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCATGGATGAAGTTATAGAGAGAGCCA
ACAATTCTGATTTTGGGCTGGTAGCTGCCGTCTTTACAAATGACATAAATAAGGCCCTGACAGTCTCTTCAG
CAATGCAGGCTGGGACAGTCTGGATAAATTGCTACAACGCCTTAAATGCCCAAAGTCCTTTTGGAGGATTCA
AAATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGATTGAGAGAATACTCTGAAGTTAAAACTGTGACGA
TAAAGATCCCTCAGAAGAACTCCTAAAATGATGAAGGACCACGTTGTGCAGAAGAGCACATGATGCCACCCT
CTCTAATCCTTATGGAGATCAGCACTCAGGAATCAAAGTGTTACACAATATATATTTAAGAAATTAAGTTGC
AACATATATACTGGGCACATAACTCTGAGCGTAATGAAACCAACTCTGCATGTTTTCATAAAACTCTCCTGA
GAATTGTTACATCTTATGAAACAAATCATAACAAGAGATAAAATTGGTATTGGGCATCATTTAATAACGGTT
CTAGCTATAAAACTGTTAAATGCAAATGCATGCACACACACATTTATCTCTTCTTTAAACAAACAAAGTCTT
AATGCTTTCAGGTTGCTTTCTCAAACAGACCTGCTTGTACTTACATTCTAGTTTCAATTAGGGCTTTACAAG
CCAGATTTTACCCAAAATGCTAGGAAAGGACAACATAAAAAACTATCATTGATGTTCTTAAAAAATAAAAGA
CTCTGAACTGTAACAAGCCCAAAGCTGGTATACTGGCAACTTTCCAATTAGCATGCTCGCATAAAGAGGTCA
AACTGGGGAGGGAATTAAACCATTATATTGGCAATGAAATCCAAATACTCATCAGTGAGATTTGGCTTTCTT
GAGCAAGGTAATTTGGTTTTCAAAGCTTCTTTTCATAATTAGTTTATGTCTTGCTATAAGCAAAAATC----
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|543740632|ref|XM_005511143.1|:3305-3524
PREDICTED: Columba livia aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
ACATCATGTTATTCAGAAATGACAGTACATTCACAGACACAGAGATGAATCAAAATATTCCTGAGTTGTTAA
ATGCAAATGCCAGGTACTTCTACTGTAGTGTATGTCAATGAAGAAAAATTAAATACAGCAAATAAGAGATTA
GTTATCTTTTAAACTGCAATATAAAATATGAAAAAGGAGATTTTACTTCTTTTCTCCTATTTACTTAAAAAA
GAAA--------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|542158262|ref|XM_005487829.1|:58-2160
PREDICTED: Zonotrichia albicollis aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CATCAGGGCAGAGCGGGGGGCTCGGTGGTGTTATAAAACCCCCCCAAGACTATGACTTCCAGTAAAATTGAG
ATGCCAGGGGAGGTGAAGGCAGATCCTGCTGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTCTC
AACCTTGAAATCAAATACACCAAGATTTTCATCAATAATGAGTGGCAGAATTCTGAAAGTGGAAGAATATTC
CCAGTATATAATCCAGCAACAGGAGAACAAATCTGTGACATTCAGGAGGCTGACAAGGTTGATACAGACAAG
GCAGTGAGGGCAGCTCGGCTGGCTTTTTCCCTGGGTTCTGTTTGGAGGAGAATGGATGCCTCAGAAAGAGGC
CATCTTTTGGATAAGTTAGCAGACTTGGTGGAAAGGGACAGGGCAATTCTTGCTACTATGGAATCACTGAAC
AGTGGCAAACCATTTTTGCAAGCTTTCTATGTAGATCTCCAGGGAGTCATAAAAACCCTGAGGTATTATGCT
GGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACATGAA
CCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTCCA
GCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGCAGAACAAACACCCCTCAGTGCTCTCTATATGGGT
GCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGTCAATATTTTGCCAGGATTTGGCCCAATTGTTGGT
GCAGCCATAGCCTCTCATGTTGGCATTGATAAAATTGCTTTCACTGGATCCACTGAGGTTGGGAAGCTGATC
CAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATTATT
TTCGCAGATGCTGATTTGGACTATGCTGTGGAACAAGCTCACCAAGGAGTCTTCTTCAATCAAGGTCAATGC
TGCACTGCAGGCTCACGGATTTATGTGGAAGAATCAATCTATGAAGAGTTTGTCAGAAGAAGTGTAGAACGT
GCAAAGAGGAGAGTTGTGGGGAGTCCTTTTGACCCAACTACAGAACAAGGTCCACAGATTGATAAAAAACAA
TACAACAAGATCTTGGAACTGATTCAAAGTGGCATCACTGAAGGAGCAAAACTTGAATGTGGGGGAAAGGGG
CTGGGAAGAAAGGGATTCTTCATTGAACCTACAGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCAAG
GAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCATGGATGAAGTTATAGAGAGAGCCAAC
AATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAAACAAGGCCCTGACAGTCTCTTCAGCA
ATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGCCTTAAATGCCCAGAGTCCTTTTGGAGGATTCAAA
ATGTCTGGCAATGGGAGAGAGATGGGCGAATGTGGATTGAGAGAATATTCTGAAGTTAAAACTGTGACAATA
AAGATCCCTCAGAAGAACTCCTAAAACTACAGAGGACCGTGTTGTGCAGAAGAGCACATGATGCCACCTTCT
CTATTCCTATGGAGACCAGCACTCAGGAATAAAAGTGTTACACAATATATATTTAAGAAATTAAGTTGCAAC
ATACATACTGGGCACATAACTGAGTACGTAATGCAAACCAACTTTGCATGTTTTCATAAAACTCTCCTGAGA
ATCGTTACATCTTTATAAAACAGATCTTAATGAGATAAAATTGCTACTGGGCATCATTTAATAATGGTTCCA
GCTATAAAACTGTTAAATGCAAATGCATGCACACACACATTTATCTCTTCCTTAAATAAACAAAATAAGTCT
TACTGCTTTCAGGTTGCCTTCTCAAACAGACCTGCCTTGTACTGACATTGTAGTTTCAATCAGGGCTCTACA
ACCCAGATTTTACCCAGAACACTAGCAATGAACAACACAAACAAGTGTCATTGATGTTCTTAAAAAATAAAA
GACTCTGAATGGTAA---------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|543256389|ref|XM_005419671.1|:57-2222
PREDICTED: Geospiza fortis aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CATCAGGGCAGAGCGGGGGGCTCGGTGGTATTATAAAACCCCCCCAAGACTATGACTTCCAGTAAAATTGAG
ATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTCTC
AACCTTGAAATCAAATACACCAAGATTTTCATCAATAATGAGTGGCAGAATTCTGAAAGTGGAAGAATATTC
CCAGTATATAATCCAGCAACAGGAGAACAAATCTGTGACATTCAGGAAGCTGACAAGGTTGATACGGACAAG
GCAGTGAGGGCAGCTCGGCTGGCTTTTTCCCTCGGTTCTGTTTGGAGGAGAATGGATGCCTCAGAAAGAGGC
CATCTTTTGGATAAGTTAGCAGACTTGGTGGAAAGGGACAGGGCAATTCTTGCTACTATGGAATCACTGAAC
AGTGGCAAACCATTTTTGCAAGCTTTCTATGTTGATCTCCAGGGAGTCATAAAAACCCTGAGGTATTATGCT
GGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACATGAA
CCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTCCA
GCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGCAGAACAAACACCACTCAGTGCTCTCTATATGGGT
GCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTGTCAATATTTTGCCAGGATTCGGTCCAATTGTTGGT
GCAGCCATAGCCTCTCATGTTGGCATTGATAAAATTGCTTTCACTGGATCCACTGAGGTTGGGAAGCTGATC
CAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATTATT
TTCGCAGATGCTGATTTGGACTATGCTGTGGAACAAGCTCACCAAGGAGTCTTCTTCAATCAAGGCCAATGC
TGCACTGCAGGCTCACGGATTTACGTGGAAGAATCGATTTACGAAGAGTTTGTCAGAAGAAGTGTAGAACGT
GCAAAAAGGAGAGTTGTGGGGAGTCCTTTTGACCCAACTACAGAACAAGGTCCACAGATTGATAAAAAACAA
TACAACAAGATCTTGGAACTGATTCAAAGTGGCATCACTGAAGGAGCAAAACTTGAATGTGGGGGAAAGGGG
CTGGGAAGAAAGGGATTCTTCATTGAACCTACAGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCAAG
GAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCATGGATGAAGTCATAGAGAGAGCCAAC
AATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATAAACAAGGCCCTGACAGTCTCTTCAGCA
ATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGCCTTAAATGCCCAAAGTCCTTTTGGAGGATTCAAA
ATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGATTGAGAGAATATTCTGAAGTTAAAACTGTGACAATA
AAGATCCCTCAGAAGAACTCCTAAAATTACAGAGGACCGTGTTGTGCAGAAGAGCACATGATGCCAACCTTC
TCTATTCCTTATGGAGACCAGCACTCAGGAATAAAAAGTGTTACACAATATATATTTAAGAAATTAAGTTGC
AACATACATACTGGGCACATAACTGAGTACGTAATGCAAACCAACTTTGCATGTTTTCATAAAACTCTCCTG
AGAATCGTTACATCTTTATAAAACAGATCTTAATGAGATAAAATTGCTACTGGGCATCATTTAATAATGGTT
CCAGCTATAAAACTGTTAAATGCAAATGCATGCACACACACACATTTATCTCTTCCTTAAATAAACAAAATA
AGTCTTACTGCTTTCAGGTTGCCTTCTCAAACAGACCTACCTTGTACTGACATTGTAGTTTCAATCAGGGCT
CTACAACCCAGATTTTACCCAGAACACTAGCAATGAACAACACAAACAAGTGTCATTGATGTTCTTAAAAAA
TAAAAGAACTCTGAATGGTAATGGCCTCAAACCTGGTATAGTGGCAACTTTCCAATTAGCACGCCCACAGAA
AGAGGT------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|525008829|ref|XM_005051999.1|:190-2294
PREDICTED: Ficedula albicollis aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CATCAGGGCAGAGCGGGGGGCTCGGTGGTGTTATAAACCCCCCCCAAGACTATGACTTCCAGTAAAATTGAG
ATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCCCTGATGGCATCTCTGCATCTGCTGCCTTCTCCCACTCTC
AACCTTGAAATCAAATACACCAAGATTTTCATCAATAATGAGTGGCAGAATTCTGAAAGTGGAAGAATATTC
CCAGTATATAATCCAGCAACAGGAGAACAAATCTGTGACATTCAGGAAGCTGACAAGGTCGACACGGACAAG
GCAGTGAGGGCAGCTCGGCTGGCTTTTTCCCTCGGTTCTGTTTGGAGGAGGATGGACGCCTCGGAAAGAGGC
CATCTTCTGGATAAGTTAGCAGACTTGGTCGAAAGGGACAGGGCAATTCTTGCTACTATGGAATCACTGAAC
AGTGGCAAACCGTTCTTGCAAGCTTTCTATGTAGATCTCCAAGGAGTCATAAAAACCTTGAGGTATTATGCT
GGTTGGGCAGACAAAATCCATGGAATGACCATTCCTGTAGATGGAGATTATTTTACGTTTACAAGACATGAA
CCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACTTCCCCCTGCTGATGTTTGCATGGAAGATTGCTCCA
GCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAGCAGAACAAACACCACTCAGTGCTCTCTATATGGGT
GCCCTCATCAAAGAGGCTGGCTTTCCACCAGGAGTTGTCAATATCTTGCCAGGATTTGGTCCAATTGTTGGT
GCAGCCATAGCCTCTCATGTTGGCATTGATAAAATTGCTTTCACTGGATCCACTGAGGTTGGGAAGCTGATC
CAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTACACTGGAGCTGGGTGGGAAAAGCCCAAACATTATT
TTCGCAGATGCTGATTTGGACTACGCTGTGGAACAAGCTCACCAAGGAGTCTTCTTCAATCAAGGTCAATGC
TGCACTGCAGGCTCACGGATTTACGTGGAAGAATCAATCTATGAAGAGTTTGTTAGAAGAAGTGTAGAACGA
GCAAAGAGGAGAGTTGTGGGGAGTCCTTTTGACCCAACTACAGAGCAAGGTCCACAGATTGATAAAAAACAA
TACAACAAGATCTTAGAACTGATTCAAAGTGGCATCACTGAAGGAGCAAAACTTGAATGTGGGGGAAAGGGG
CTGGGAAGAAAGGGATTCTTCATTGAACCTACAGTGTTTTCCAATGTAACAGATGACATGCGGATTGCCAAG
GAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGATTTAAAACCATGGATGAAGTTATAGAGAGAGCCAAC
AATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAAATGACATCAACAAGGCCCTGACGGTCTCTTCAGCA
ATGCAGGCTGGGACAGTCTGGATAAATTGCTACAATGCCTTAAATGCCCAAAGTCCTTTTGGAGGATTCAAA
ATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGATTGAGAGAATATTCTGAAGTTAAAACTGTGACAATA
AAGATCCCTCAGAAGAACTCCTAAAATGACAAAGGACCGTGTTGTGCAGAAGAGCACATGATGCCACCTTCT
CTATTCCTTATGGAGACCAGCACTCAGGAATAAAAAGTGTTACACAATATATATTTAAGAAATTAAGTTGCA
ACATATATACTGGGTACATAACTGCGTACGTAATACAAACCAACTCTGCATGTTTTCATAAAACTCTCCTGA
GAATCGTTACATCTTTATAAAACAAATCATAATGAGATAAAATTGCTACTGGGCATCATTTAATAATGGTTC
CAGCTATAAAACTGTTAAATGCAAATGCATGCACGCACACATTTATGTCTTCCTTAAATAAACAAAATAAGT
CTTACTGCTTTCAGGTTGCCTTCTCGAACAGACCTGCCTTGTACTGACATCGTAGTTTCAATCAGGGCTCTA
CAAGACAGATTATACTGAAAACACTAGCAATGAGCAACACAAACAACTGTCATTGATGTTCTTAAAAAATAA
AAGACTCTGAATGGTAA-------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
>N1;gi|543353810|ref|XM_005521466.1|:97-1989
PREDICTED: Pseudopodoces humilis aldehyde dehydrogenase 1 family, member A2 (ALDH1A2), transcript variant X1, mRNA
CCCCTCCCAAGACTATGACTTCCAGTAAAATTGAGATGCCAGGGGAGGTGAAGGCAGATCCTGCAGCTCTGA
TGGCATCTCTGCATCTGCTCCCTTCTCCCACTCTCAACCTTGAAATCAAATACACCAAGATTTTCATCAATA
ATGAGTGGCAGAATTCTGAAAGTGGAAGAATATTCCCAGTATATAATCCAGCAACAGGAGAACAAATCTGTG
ACATTCAGGAAGCTGACAAAGTTGATACAGACAAGGCAGTGAGGGCAGCTCGGCTGGCTTTTTCCCTGGGGT
CCGTTTGGAGGAGAATGGATGCCTCAGAAAGAGGCCATCTTTTGGATAAGTTAGCAGACTTGGTCGAAAGGG
ACAGGGCAATTCTTGCTACTATGGAATCACTGAACAGTGGCAAACCATTCTTGCAAGCTTTCTATGTAGATC
TCCAGGGAGTCATAAAAACCCTGAGGTATTATGCTGGCTGGGCAGACAAAATCCATGGAATGACCATTCCTG
TAGATGGAGATTATTTTACGTTTACAAGACATGAACCCATCGGAGTGTGTGGACAGATCATCCCTTGGAACT
TCCCCCTGCTGATGTTTGCATGGAAGATTGCTCCTGCTCTGTGCTGTGGCAATACAGTAGTTATTAAACCAG
CCGAACAAACACCACTCAGTGCTCTCTACATGGGTGCCCTCATCAAGGAGGCTGGCTTTCCACCAGGAGTTG
TCAATATTTTGCCAGGATTTGGTCCAATTGTTGGTGCAGCCATAGCCTCTCACGTTGGCATTGATAAAATTG
CTTTCACTGGATCCACTGAGGTTGGGAAGCTGATCCAAGAAGCAGCTGGAAGGAGTAATTTGAAGAGAGTTA
CACTGGAGCTGGGTGGGAAAAGCCCAAACATTATTTTCGCAGATGCTGATTTGGACTATGCTGTGGAACAAG
CTCACCAAGGAGTCTTCTTCAACCAAGGACAGTGCTGCACTGCAGGCTCACGGATTTACGTGGAAGAATCAA
TCTACGAAGAGTTTGTCAGAAGGAGCGTAGAACGTGCAAAGAGGAGAGTTGTGGGGAGTCCTTTTGACCCAA
CTACAGAACAAGGTCCACAGATTGATAAAAAACAATACAACAAGATCTTGGAACTGATTCAAAGTGGCATCA
CTGAAGGAGCAAAACTTGAATGTGGGGGAAAGGGGCTGGGAAGAAAGGGATTCTTCATTGAACCTACAGTGT
TTTCCAATGTAACAGATGACATGCGGATTGCCAAGGAGGAGATTTTTGGGCCTGTTCAAGAAATACTGAGAT
TTAAAACCATGGATGAAGTTATAGAGAGAGCCAACAATTCTGATTTTGGGCTGGTAGCTGCTGTCTTTACAA
ATGACATAAACAAGGCCCTGACAGTCTCTTCAGCAATGCAGGCTGGGACGGTCTGGATAAATTGCTACAATG
CCTTAAATGCCCAAAGTCCTTTTGGAGGATTCAAAATGTCTGGCAATGGGAGAGAGATGGGTGAATGTGGAT
TGAGAGAATATTCTGAAGTTAAAACTGTGACAATAAAGATCCCTCAGAAGAACTCCTAAAACGACAGAGGAC
CGTGTTGTGCAGAAGAGCACATGATGCCACCTTCTCTATTCCTTATGGAGACCAGCACTCAGGAATAAAAAG
TGTTACACAATATTTAAGAAATTAAGTTGCAACATATATACTGGGCACATAACTGCATACGTAATGCAAACC
AACTCTGCATGTTTTCATGAAAATCTCCTGAGAATCGTTACATCTTTTTAAAACAAATTATAATGAGATAAA
ATTGCTACTGGGCATCATTTAATAACGGTTCCAGCTATAAAACTGTTAAATGCAAATGCATGCACACACACA
TTTATCTCTTCCTTAAATAAA---------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------------*
